# Within your codeup-data-science directory, create a directory named statistics-exercises. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub.

# Do your work for this exercise in either a python file named simulation.py or a jupyter notebook named simulation.ipynb.

# 1. How likely is it that you roll doubles when rolling two dice?

In [4]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [24]:
n_trials = n_rows = 1_000
n_dice = n_cols = 2
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(n_rows, n_cols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [3, 6],
       [1, 6],
       [3, 1]])

In [25]:
dice1= np.random.choice([1,2,3,4,5,6],10000)
dice2=np.random.choice([1,2,3,4,5,6],10000)
samesies= dice1==dice2
samesies.mean()

0.1627

# Next Method

In [3]:
# set number of trials and events per trial

nrows = 100_000 # number of trials
ncols = 2       # number of random events in each trial

In [5]:
# generate an array of randomly generated numbers from 1-6 equal to the number of rows times the number of columns
# to generate all of the values for the study
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols)

array([6, 4, 5, ..., 5, 6, 5])

In [6]:
# add .reshape to reshape the array by the number of rows and number of columns to create trial groups
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)
rolls

array([[2, 6],
       [6, 1],
       [5, 2],
       ...,
       [2, 5],
       [4, 6],
       [3, 2]])

In [7]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1
0  2  6
1  6  1
2  5  2
3  5  2
4  6  1

In [8]:
# add .apply create an array that checks weather each row contains matching numbers
df.apply(lambda row: row[0] == row[1], axis=1)

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [9]:
# add .mean to get the mean of that array to get the odds of rolling doubles on two six sided dice
df.apply(lambda row: row.values[0] == row.values[1], axis=1).mean()

0.16819

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [24]:
nrows = 100_000
ncols = 8
np.random.choice([True, False], nrows * ncols)
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)
rolls
df = pd.DataFrame(rolls)
df.head()
three_heads = df.apply(lambda row: row.values.sum() == 3, axis=1).mean()
more_than_three_heads = df.apply(lambda row: row.values.sum() > 3, axis=1).mean()
three_heads

0.21844

In [25]:
more_than_three_heads

0.63785

# Next Method

In [26]:
trails= 1000
coins= 8 
flips =np.random.choice(["heads", "Tails"], size =(trails, coins))
flips 

array([['heads', 'heads', 'heads', ..., 'heads', 'Tails', 'heads'],
       ['heads', 'Tails', 'Tails', ..., 'heads', 'Tails', 'Tails'],
       ['heads', 'Tails', 'heads', ..., 'heads', 'heads', 'Tails'],
       ...,
       ['Tails', 'Tails', 'heads', ..., 'heads', 'heads', 'heads'],
       ['heads', 'heads', 'Tails', ..., 'Tails', 'heads', 'Tails'],
       ['Tails', 'heads', 'heads', ..., 'heads', 'heads', 'Tails']],
      dtype='<U5')

In [27]:
flips = pd.DataFrame(flips, columns=["first_coin", "second_coin","third_coin", "fourth_coin", "fifth_coin", "sixth_coin", "seventh_coin","eighth_coin"])
flips.head(20)

first_coin second_coin third_coin fourth_coin fifth_coin sixth_coin  \
0       heads       heads      heads       Tails      Tails      heads   
1       heads       Tails      Tails       Tails      heads      heads   
2       heads       Tails      heads       Tails      heads      heads   
3       heads       heads      heads       heads      heads      heads   
4       heads       heads      Tails       heads      Tails      Tails   
5       Tails       Tails      heads       heads      heads      heads   
6       Tails       heads      heads       heads      Tails      heads   
7       Tails       Tails      Tails       Tails      heads      heads   
8       heads       heads      heads       heads      heads      Tails   
9       heads       heads      heads       Tails      heads      Tails   
10      Tails       Tails      Tails       Tails      Tails      Tails   
11      Tails       heads      Tails       Tails      heads      heads   
12      Tails       Tails      heads       heads      Tails      heads   
13      heads       heads      Tails       Tails      Tails      Tails   
14      heads       Tails      Tails       Tails      heads      heads   
15      heads       Tails      Tails       heads      heads      heads   
16      Tails       heads      heads       Tails      Tails      heads   
17      heads       Tails      heads       Tails      heads      Tails   
18      Tails       heads      heads       Tails      Tails      heads   
19      heads       Tails      heads       Tails      Tails      Tails   

   seventh_coin eighth_coin  
0         Tails       heads  
1         Tails       Tails  
2         heads       Tails  
3         Tails       Tails  
4         Tails       Tails  
5         heads       Tails  
6         Tails       Tails  
7         heads       heads  
8         Tails       heads  
9         Tails       Tails  
10        heads       heads  
11        Tails       Tails  
12        Tails       heads  
13        Tails       heads  
14        heads       heads  
15        Tails       Tails  
16        heads       Tails  
17        Tails       Tails  
18        Tails       Tails  
19        heads       heads

In [28]:
def count_heads(row):
  return row.first_coin.count("heads") + row.second_coin.count("heads")+row.third_coin.count("heads")+row.fourth_coin.count("heads")+row.fifth_coin.count("heads")+row.sixth_coin.count("heads")+row.seventh_coin.count("heads")+row.eighth_coin.count("heads")

In [29]:
flips["head_count"] = flips.apply(count_heads, axis=1)
flips

first_coin second_coin third_coin fourth_coin fifth_coin sixth_coin  \
0        heads       heads      heads       Tails      Tails      heads   
1        heads       Tails      Tails       Tails      heads      heads   
2        heads       Tails      heads       Tails      heads      heads   
3        heads       heads      heads       heads      heads      heads   
4        heads       heads      Tails       heads      Tails      Tails   
..         ...         ...        ...         ...        ...        ...   
995      heads       Tails      heads       Tails      Tails      heads   
996      heads       Tails      Tails       Tails      Tails      Tails   
997      Tails       Tails      heads       Tails      Tails      heads   
998      heads       heads      Tails       Tails      Tails      Tails   
999      Tails       heads      heads       heads      heads      heads   

    seventh_coin eighth_coin  head_count  
0          Tails       heads           5  
1          Tails       Tails           3  
2          heads       Tails           5  
3          Tails       Tails           6  
4          Tails       Tails           3  
..           ...         ...         ...  
995        heads       heads           5  
996        Tails       Tails           1  
997        heads       heads           4  
998        heads       Tails           3  
999        heads       Tails           6  

[1000 rows x 9 columns]

In [30]:
# flipping exactly three heads?
flips[(flips.head_count == 3)]

first_coin second_coin third_coin fourth_coin fifth_coin sixth_coin  \
1        heads       Tails      Tails       Tails      heads      heads   
4        heads       heads      Tails       heads      Tails      Tails   
11       Tails       heads      Tails       Tails      heads      heads   
13       heads       heads      Tails       Tails      Tails      Tails   
17       heads       Tails      heads       Tails      heads      Tails   
..         ...         ...        ...         ...        ...        ...   
989      heads       Tails      heads       Tails      Tails      heads   
990      Tails       heads      Tails       Tails      Tails      heads   
992      Tails       Tails      heads       Tails      heads      Tails   
994      heads       Tails      Tails       heads      heads      Tails   
998      heads       heads      Tails       Tails      Tails      Tails   

    seventh_coin eighth_coin  head_count  
1          Tails       Tails           3  
4          Tails       Tails           3  
11         Tails       Tails           3  
13         Tails       heads           3  
17         Tails       Tails           3  
..           ...         ...         ...  
989        Tails       Tails           3  
990        heads       Tails           3  
992        Tails       heads           3  
994        Tails       Tails           3  
998        heads       Tails           3  

[245 rows x 9 columns]

In [31]:
flips[(flips.head_count > 3)]

first_coin second_coin third_coin fourth_coin fifth_coin sixth_coin  \
0        heads       heads      heads       Tails      Tails      heads   
2        heads       Tails      heads       Tails      heads      heads   
3        heads       heads      heads       heads      heads      heads   
5        Tails       Tails      heads       heads      heads      heads   
6        Tails       heads      heads       heads      Tails      heads   
..         ...         ...        ...         ...        ...        ...   
991      Tails       Tails      Tails       heads      Tails      heads   
993      heads       Tails      heads       Tails      heads      Tails   
995      heads       Tails      heads       Tails      Tails      heads   
997      Tails       Tails      heads       Tails      Tails      heads   
999      Tails       heads      heads       heads      heads      heads   

    seventh_coin eighth_coin  head_count  
0          Tails       heads           5  
2          heads       Tails           5  
3          Tails       Tails           6  
5          heads       Tails           5  
6          Tails       Tails           4  
..           ...         ...         ...  
991        heads       heads           4  
993        heads       Tails           4  
995        heads       heads           5  
997        heads       heads           4  
999        heads       Tails           6  

[614 rows x 9 columns]

In [32]:
(flips.head_count > 3).mean()

0.614

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?


In [94]:
trails= 1000
cohort= 2 
bill_board =np.random.choice(["web", "web", "web", "data"], size =(trails, cohort))
bill_board

array([['data', 'data'],
       ['web', 'data'],
       ['web', 'web'],
       ...,
       ['web', 'web'],
       ['web', 'web'],
       ['data', 'web']], dtype='<U4')

In [96]:
bill_board= pd.DataFrame(bill_board, columns= ["A", "B"])
bill_board.head(10)

A     B
0  data  data
1   web  data
2   web   web
3   web  data
4  data  data
5   web   web
6   web   web
7   web  data
8   web  data
9   web   web

In [97]:
bill_board = pd.DataFrame(bill_board, columns=["A", "B"])
bill_board.head(20)

A     B
0   data  data
1    web  data
2    web   web
3    web  data
4   data  data
5    web   web
6    web   web
7    web  data
8    web  data
9    web   web
10   web  data
11   web   web
12   web  data
13   web   web
14   web   web
15  data  data
16  data   web
17   web  data
18   web   web
19  data   web

In [98]:
def count_data(row):
  return row.A.count("data") + row.B.count("data")

In [99]:
# Let's setup a 3rd column to count the number of data scientists  
bill_board["count_data"] = bill_board.apply(count_data, axis=1)
bill_board

A     B  count_data
0    data  data           2
1     web  data           1
2     web   web           0
3     web  data           1
4    data  data           2
..    ...   ...         ...
995   web   web           0
996   web   web           0
997   web   web           0
998   web   web           0
999  data   web           1

[1000 rows x 3 columns]

In [101]:
#odds having 2 data scientists 
bill_board[(bill_board.count_data == 2)]

A     B  count_data
0    data  data           2
4    data  data           2
15   data  data           2
24   data  data           2
44   data  data           2
..    ...   ...         ...
860  data  data           2
930  data  data           2
947  data  data           2
959  data  data           2
965  data  data           2

[72 rows x 3 columns]

In [103]:
(bill_board.count_data == 2).mean()

0.072

# Next Method

In [30]:
nrows = 100_000
ncols = 2
np.random.choice(['data', 'data', 'data', 'web'], nrows * ncols)
rolls = np.random.choice(['data', 'data', 'data', 'web'], nrows * ncols).reshape(nrows, ncols)
rolls
df = pd.DataFrame(rolls)
df.head()
both_df = df.apply(lambda row: (row.values[0] == "data") and (row.values[1] == "data"), axis=1).mean()
both_df

0.56339

# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)


In [105]:
poptarts = np.random.normal(3, 1.5, size=(100000,5))
poptarts

array([[ 3.23570969,  2.98332103,  1.82489968,  0.25897515,  2.94039462],
       [ 3.33713169,  4.60182305,  3.20395972,  0.85320577,  2.85662151],
       [-0.71508479,  3.14031238,  1.84603806,  2.77095528,  0.32618449],
       ...,
       [ 1.99655361,  2.42692756,  1.74172922,  3.86615849,  0.82222605],
       [ 3.21570305,  2.57121954,  0.7776136 ,  1.88394721,  1.36712788],
       [ 3.25360284,  2.71352096,  1.9855653 ,  1.9340058 ,  1.36873593]])

In [106]:
poptarts = np.round(np.random.normal(3, 1.5, size=(100000,5)))
poptarts[0]

array([4., 1., 3., 2., 4.])

In [107]:
weekly_demand = poptarts.sum(axis=1)

In [109]:
weekly_demand <17

array([ True, False,  True, ...,  True,  True, False])

In [110]:
(weekly_demand <17).mean()

0.66951

# Next Method

In [33]:
nrows = 100_000 # set rows to number of simulations
ncols = 5       # set columns to number of days in each simulation

# create an array of values using random.normal to repesent the number of PopTarts bought in a day
# reshabe that array into trial groups of 5 to represent five days or PopTart buying
rolls = np.random.normal(3, 1.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1  2  3  4
0  2  5  1  2  0
1  1  4  0  2  0
2  2  1  3  2  3
3  0  3  4  2  0
4  4  2  1  1  2

In [35]:
# count the number of bought PopTarts in each row and create a boolean array showing weather the total number of bought PopTarts equals or exceeds 17
# take the mean of the array to get the probability of having poptarts available to by on friday afternoon
odds_of_tarts = df.apply(lambda row: row.values.sum() < 17, axis=1).mean()

odds_of_tarts


0.87934

# 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [111]:
np.random.seed(29)
p_m = np.random.normal(178,8,100_000)
p_w = np.random.normal(170,6,100_000)
p_w
p_m

(p_w > p_m).mean()

0.21252

# Next Method

In [36]:
# use random.normal to create arrays representing male and female hights chosen at random
male_hights = np.random.normal(178, 8, 100_000)
female_hights = np.random.normal(170, 6, 100_000)

# convert the arrays to a to single dataframe where each row reprsents a female and male hight chosen at random
df = pd.DataFrame({"male_hights" : male_hights,
                   "female_hights" : female_hights})

# add boolean column showing true if the female hight is greater in each row (trial)
df['female_is_taller'] = df.female_hights > df.male_hights
df

male_hights  female_hights  female_is_taller
0       174.903222     170.495748             False
1       177.285285     168.120946             False
2       183.010967     168.843249             False
3       191.867843     170.627692             False
4       181.973178     167.359275             False
...            ...            ...               ...
99995   168.410358     168.801606              True
99996   191.882067     170.759778             False
99997   169.398737     164.963748             False
99998   183.103165     170.804485             False
99999   168.773391     169.175091              True

[100000 rows x 3 columns]

In [37]:
# get mean of that column
taller_female = df['female_is_taller'].mean()
taller_female

0.21283

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

# How likely is it that 450 students all download anaconda without an issue?



In [116]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 50), p = (1/250, 249/250))

In [113]:
((fails == 'success').sum(axis=1) == 50).mean() # probability of 50 successes

0.81708

In [118]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 100), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 100).mean() # probability of 100 successes

0.66895

In [119]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 150), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 150).mean() # probability of 150 successes

0.54671

In [120]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 450), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 450).mean() # probability of 450 successes

0.16459

# Next Method

In [38]:
def anaconda_problem(number_of_students):
    
    nrows = 100_000 # set rows to number of simulations
    ncols = number_of_students # set columns to number of students in each simulation

    # create list with 249 falses and one true
    issue_range = [False for r in range(1,250)]
    issue_range.append(True)

    # use random.choice to create an arrepresenting whether there was an issue with a given student's Anaconda install
    # reshape the dataframe into trial groups of the desiered number of students
    installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(installs)

    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds of not encountering any problems in the trial group
    no_problems = df.apply(lambda row: row.values.sum() == 0, axis=1).mean()
    
    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds encountering any problems in the trial group
    problems = df.apply(lambda row: row.values.sum() > 0, axis=1).mean()

    print(f'The odds of {number_of_students} students downloading Anaconda without a problem are {round(no_problems*100)}%')
    print(f'The odds of {number_of_students} students downloading Anaconda encountering at least one problem are {round(problems*100)}%')

In [39]:
anaconda_problem(50)

The odds of 50 students downloading Anaconda without a problem are 82%
The odds of 50 students downloading Anaconda encountering at least one problem are 18%


In [40]:
anaconda_problem(100)

The odds of 100 students downloading Anaconda without a problem are 67%
The odds of 100 students downloading Anaconda encountering at least one problem are 33%


In [41]:
anaconda_problem(150)

The odds of 150 students downloading Anaconda without a problem are 55%
The odds of 150 students downloading Anaconda encountering at least one problem are 45%


In [42]:
anaconda_problem(450)

The odds of 450 students downloading Anaconda without a problem are 17%
The odds of 450 students downloading Anaconda encountering at least one problem are 83%


# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?

In [43]:
trucks= np.random.choice(['seen', 'no_seen'], size = (100_000,3), p = ([0.7, 0.3]))
((trucks == 'no_seen').sum(axis = 1) == 3).mean()


0.02694

In [45]:
trucks= np.random.choice(['seen', 'no_seen'], size = (100_000,3), p = ([0.7, 0.3]))
((trucks == 'seen').sum(axis = 1) >= 1).mean()

0.97401

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [46]:
def shared_birthday(people):

    nrows = 100_000 # set rows to number of simulations
    ncols = people  # set columns to number of people in each simulation

    # create array with each value representing the numbered day of the year that person was born on. (This ignores leap years)
    # reshape the aray into trial groups
    sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Add boolian column to df showing weather there are less unique numbers in each row (trial) than there are total columns
    df['matching_birthdays'] = df.nunique(axis=1) < ncols

    # get mean of calculation True/False columns
    # format and print results
    matching_birthdays = df['matching_birthdays'].mean()

    # print result
    print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {round(matching_birthdays*100)}%')

In [47]:
num_list = [23, 20, 40]

for num in num_list:
    shared_birthday(num)

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 40 people having at least two people that share a birthday are 89%
